### PR TITLE
Use personal-files and switch to strict confinement

### PR DESCRIPTION
**Pull request by anonymouse64**
* Use core18 base
* Use strict confinement with personal-files for $HOME/.aws
* Add launcher part to pull launcher script from gallery-dl to correctly determine the user's actual $HOME outside of snap confinement
* Plug network, network-bind and home for the aws app
* Specify adapter: full and use command-chain to avoid creating additional wrapper scripts

Note that you could probably copy the relevant snippet from launcher part and use that instead of copying it in, but I thought it was simplest to just copy it over.

### CODE REVIEW

**Comment by anonymouse64** [comment]
Also note that before you can publish the snap in the store with the personal-files interface here, you will need to request permission on the snapcraft forum at forum.snapcraft.io as per https://forum.snapcraft.io/t/process-for-aliases-auto-connections-and-tracks/455

**Comment by anonymouse64** [comment]
Also also you may want to just copy in the wrapper script here and drop the removable-media check here: 
https://github.com/mikf/gallery-dl/blob/62335b9015467861a26addfd65cdfb843aadfe0c/snap/local/launchers/gallery-dl-launch#L17-L29

and just use the $HOME extraction part here:
https://github.com/mikf/gallery-dl/blob/62335b9015467861a26addfd65cdfb843aadfe0c/snap/local/launchers/gallery-dl-launch#L10-L15

**Review by davdunc — APPROVED** [review]
Thanks. Good to ignore.

**Comment by davdunc** [comment]
Merging in these changes.

**Comment by anonymouse64** [comment]
Thanks! any idea when this will be released? You will also need to request usage of the personal-files interface on the forum as per https://forum.snapcraft.io/t/process-for-aliases-auto-connections-and-tracks/455 before this can be uploaded to the store and released successfully

**Pull request merged**
